// LOGIN

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

// SIGNUP

// export const SIGNUP_INIT = "SIGNUP_INIT";
// export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
// export const SIGNUP_ERROR = "SIGNUP_ERROR";

// PROFILE
export const USER_PROFILE = "USER_PROFILE";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const CHECK_LOCATION_VALID = "CHECK_LOCATION_VALID";

// TUTOR
export const GET_TUTOR = "GET_TUTOR";
export const GET_TUTOR_SUCCESS = "GET_TOTUR_SUCCESS";
export const GET_TUTOR_FAILURE = "GET_TUTOR_FAILURE";

// CHECK IN
export const CHECK_IN = "CHECK_IN";
export const CHECK_IN_SUCCESS = "CHECK_IN_SUCCESS";
export const CHECK_IN_FAILURE = "CHECK_IN_FAILURE";

// CHECK OUT
export const CHECK_OUT = "CHECK_OUT";
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS";
export const CHECK_OUT_FAILURE = "CHECK_OUT_FAILURE"

// CALENDAR
export const CALENDAR = "CALENDAR";
export const CALENDAR_SUCCESS = "CALENDAR_SUCCESS";
export const CALENDAR_FAILURE = "CALENDAR_FAILURE";

// WORK LOGS
export const WORK_LOGS = "WORKLOGS";
export const WORK_LOGS_SUCCESS = "WORK_LOGS_SUCCESS";
export const WORK_LOGS_FAILURE = "WORK_LOGS_FAILURE";

// REGULARIZE
export const REGULARIZE = "REGULARIZE";
export const REGULARIZE_SUCCESS = "REGULARIZE_SUCCESS";
export const REGULARIZE_FAILURE = "REGULARIZE_FAILURE";

// EMPLOYEE LIST
export const EMPLOYEE_LIST = "EMPLOYEE_LIST";
export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCESS";
export const EMPLOYEE_LIST_FAILURE = "EMPLOYEE_LIST_FAILURE";

// ADD USER
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

// EDIT EMPLOYEE
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILURE = "EDIT_EMPLOYEE_FAILURE";

// GET EMPLOYEE DETAILS
export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS";
export const GET_EMPLOYEE_DETAILS_SUCCESS = "GET_EMPLOYEE_DETAILS_SUCCESS";
export const GET_EMPLOYEE_DETAILS_FAILURE = "GET_EMPLOYEE_DETAILS_FAILURE";

// CHANGE PASSWORD
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";   
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// CHANGE STATUS
export const CHANGE_STATUS = "CHANGE_STATUS";
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_FAILURE = "CHANGE_STATUS_FAILURE"; 

// PROJECTS LIST
export const PROJECTS_LIST = "PROJECTS_LIST";
export const PROJECTS_LIST_SUCCESS = "PROJECTS_LIST_SUCCESS";
export const PROJECTS_LIST_FAILURE = "PROJECTS_LIST_FAILURE";

// COMPANY LIST 
export const COMPANY_LIST = "COMPANY_LIST";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_LIST_FAILURE = "COMPANY_LIST_FAILURE";